# Generated by Django 5.2.13 on 2026-04-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='remote_type',
            field=models.CharField(blank=True, choices=[('remote', 'Fully Remote'), ('hybrid', 'Hybrid'), ('on-site', 'On-Site')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_period',
            field=models.CharField(blank=True, choices=[('annual', 'Yearly'), ('monthly', 'Monthly'), ('hourly', 'Hourly')], max_length=20),
        ),
    ]
