# Generated by Django 5.2.13 on 2026-04-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobpostingrequest_resumesubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpostingrequest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='resumesubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='jobpostingrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes — not visible to submitter'),
        ),
        migrations.AddField(
            model_name='jobpostingrequest',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpostingrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jobpostingrequest',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpostingrequest',
            name='job_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpostingrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumesubmission',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal admin notes'),
        ),
        migrations.AlterField(
            model_name='jobpostingrequest',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpostingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved — Published'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resumesubmission',
            name='position',
            field=models.CharField(blank=True, help_text='Job title or position they are applying for', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumesubmission',
            name='resume',
            field=models.FileField(upload_to='resumes/%Y/%m/'),
        ),
    ]
