# Generated by Django 5.2.13 on 2026-04-27 09:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobpostingrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jobpostingrequest',
            name='job_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jobpostingrequest',
            name='job_requirements',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
