# Generated by Django 5.2 on 2026-05-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_description_alter_job_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_partner',
            field=models.BooleanField(default=False, help_text="Show this company in the 'Partners' section on the Home page"),
        ),
    ]
