# Generated by Django 5.2 on 2026-05-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_company_description_alter_company_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesubmission',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/'),
        ),
    ]
