# Generated by Django 5.2.13 on 2026-04-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('job-seekers', 'For Job Seekers'), ('employers', 'For Employers'), ('platform', 'Platform & Account'), ('adsense', 'General')], default='job-seekers', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Career Builders Hub', max_length=100)),
                ('site_tagline', models.CharField(default='Entry-Level Jobs for Recent Graduates', max_length=200)),
                ('hero_heading', models.CharField(default='Launch Your Career with Confidence', max_length=200)),
                ('hero_subtext', models.TextField(default='Browse verified entry-level jobs curated for recent graduates.')),
                ('hero_cta_text', models.CharField(default='Browse All Jobs', max_length=100)),
                ('about_intro', models.TextField(blank=True)),
                ('contact_email', models.EmailField(default='hello@careerbuildershub.com', max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('ga_measurement_id', models.CharField(blank=True, help_text='Google Analytics 4 Measurement ID, e.g. G-XXXXXXXXXX', max_length=50)),
                ('adsense_publisher_id', models.CharField(blank=True, help_text='AdSense Publisher ID, e.g. pub-XXXXXXXXXXXXXXXX — only fill after approval', max_length=50)),
                ('adsense_enabled', models.BooleanField(default=False, help_text='ONLY enable after AdSense application is approved')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
