# Generated by Django 5.2 on 2026-05-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fix_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('seekers', 'For Job Seekers'), ('employers', 'For Employers')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hiw_video_employers',
            field=models.TextField(blank=True, help_text='YouTube iframe embed code for Employers'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hiw_video_seekers',
            field=models.TextField(blank=True, help_text='YouTube iframe embed code for Job Seekers'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='support@jobfoundryhub.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Job Foundry Hub', max_length=100),
        ),
    ]
