# Generated by Django 5.2 on 2026-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_howitworksstep_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howitworksstep',
            options={'ordering': ['category', 'order'], 'verbose_name': 'How It Works Step', 'verbose_name_plural': 'How It Works Steps'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='hiw_video_employers',
            new_name='hiw_video_embed_employers',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='hiw_video_seekers',
            new_name='hiw_video_embed_seekers',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hiw_video_file_employers',
            field=models.FileField(blank=True, help_text='Upload a video file for Employers', null=True, upload_to='videos/hiw/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hiw_video_file_seekers',
            field=models.FileField(blank=True, help_text='Upload a video file for Job Seekers', null=True, upload_to='videos/hiw/'),
        ),
    ]
