# Generated by Django 5.2 on 2026-05-30 13:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_howitworksstep_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hiw_video_file_employers',
            field=models.FileField(blank=True, help_text='Upload a video file for Employers', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/hiw/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hiw_video_file_seekers',
            field=models.FileField(blank=True, help_text='Upload a video file for Job Seekers', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/hiw/'),
        ),
    ]
