# Generated by Django 5.2 on 2026-06-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sitesettings_hiw_video_file_employers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='monetag_enabled',
            field=models.BooleanField(default=False, help_text='Enable Monetag ads on the site'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='monetag_head_script',
            field=models.TextField(blank=True, help_text='Paste the Monetag JS snippet here (Vignette or In-Page Push)'),
        ),
    ]
