# Generated by Django 5.2 on 2026-06-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_monetag_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_rewrite_enabled',
            field=models.BooleanField(default=True, help_text='Use Gemini to rewrite job descriptions during sync. If off, the raw + template description is used.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_api_keys',
            field=models.TextField(blank=True, help_text='Gemini API key(s), ONE PER LINE. Multiple keys are rotated to raise the rate limit (each key allows ~15 requests/min).'),
        ),
    ]
