# Generated by Django 5.2 on 2026-04-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='meta_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='meta_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(max_length=200),
        ),
    ]
