# Generated by Django 5.2 on 2026-05-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcategory_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
