# Generated by Django 5.2.13 on 2026-04-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='source',
            field=models.CharField(blank=True, help_text='Where they subscribed from: homepage, blog, footer, etc.', max_length=100),
        ),
    ]
