from django.core.management.base import BaseCommand
from apps.jobs.models import Company

class Command(BaseCommand):
    help = 'Seeds highly detailed, 400-600 word authentic company profiles for our top employers.'

    def handle(self, *args, **options):
        # Dictionary of highly detailed, authentic descriptions for top employers.
        profiles = {
            "EV Cargo": """<p>EV Cargo is a global logistics execution and supply chain services platform that manages complex supply chains for major brands worldwide. Founded in 2018 by the Hong Kong-based investment firm EmergeVest, the company was formed through a strategic "buy and build" initiative that successfully integrated various established freight forwarding, logistics, and supply chain technology companies into a single powerhouse.</p>
            <p>At its core, EV Cargo provides an integrated, end-to-end range of services across international and domestic supply chains. Their Air and Sea Freight divisions offer robust international freight forwarding, including highly complex multimodal solutions that connect manufacturers and retailers across global trade lanes. In addition to maritime and aviation logistics, they operate as a significant road freight provider across the UK and Europe, managing both full-truckload (FTL) and less-than-truckload (LTL) services through an expansive proprietary fleet and partner networks.</p>
            <p>Beyond transportation, EV Cargo specializes in Contract Logistics and Warehousing. They provide bespoke storage, fulfillment, and specialized "final mile" delivery solutions. By offering agile, on-demand warehousing facilities, they empower businesses to efficiently manage inventory constraints and adapt to sudden market demand fluctuations. These physical operations are tightly integrated with their proprietary Supply Chain Software, the "ONE EV Cargo" digital platform, which aggregates supply chain data to provide unprecedented visibility, tracking, and management tools for their corporate customers.</p>
            <p>Today, EV Cargo boasts a massive operational reach, maintaining physical offices in over 25 countries and operating in more than 150 countries through a deeply vetted network of strategic partners. They maintain major regional supply chain hubs in key strategic locations including London, Dubai, Singapore, and Hong Kong. The organization strongly emphasizes a technology-enabled approach to global logistics, with a core corporate mission to make international supply chains dramatically more sustainable, transparent, and efficient through continuous digital transformation and workforce development.</p>""",

            "ChampionX": """<p>ChampionX is a globally recognized leader in chemistry solutions, artificial lift systems, and highly engineered equipment and technologies that help companies drill for and produce oil and gas safely, efficiently, and sustainably around the world. As a premier partner to the energy sector, ChampionX boasts over a century of profound industry expertise, blending deep technical knowledge with cutting-edge technological advancements to solve some of the most complex challenges in modern energy production.</p>
            <p>The company operates across multiple critical segments within the upstream and midstream energy sectors. Their Production Chemical Technologies division develops and deploys proprietary chemical solutions that maximize production rates, extend the life of critical infrastructural assets, and significantly reduce the environmental footprint of extraction processes. These specialized chemical applications are essential for ensuring flow assurance, maintaining asset integrity, and separating oil, water, and natural gas safely.</p>
            <p>In addition to chemical solutions, ChampionX is a market leader in Artificial Lift Technologies. They design, manufacture, and implement advanced electrical submersible pumping (ESP) systems, gas lift equipment, and monitoring technologies that artificially stimulate well production when natural reservoir pressures decline. Their integrated approach combines robust hardware with intelligent, data-driven software platforms that allow operators to remotely monitor, analyze, and optimize well performance in real-time.</p>
            <p>Sustainability and environmental stewardship are foundational to ChampionX's modern corporate strategy. The organization is deeply committed to helping the energy industry transition toward a lower-carbon future. Through relentless research and development, ChampionX continuously innovates solutions that minimize greenhouse gas emissions, reduce fresh water usage, and ensure operational safety. With a diverse global workforce spanning multiple continents, the company fosters an inclusive, purpose-driven culture that prioritizes continuous learning, employee safety, and community engagement.</p>""",

            "A-List Marketing": """<p>A-List Marketing is a dynamic and fast-growing direct sales and marketing firm dedicated to helping ambitious brands expand their market share and acquire high-quality customers. Operating at the intersection of strategic consulting and direct consumer engagement, A-List Marketing specializes in designing and executing highly targeted, face-to-face marketing campaigns that bypass the noise of traditional digital advertising and deliver measurable, immediate ROI for their corporate clients.</p>
            <p>The company’s core methodology revolves around the power of interpersonal communication and relationship-building. Unlike passive marketing channels such as email or social media, A-List Marketing deploys trained, professional representatives to engage directly with potential customers in commercial, retail, and event-based environments. This direct approach allows for real-time brand storytelling, instant feedback collection, and highly personalized product demonstrations that significantly increase conversion rates and foster long-term brand loyalty.</p>
            <p>A-List Marketing is deeply committed to the professional development and continuous training of its workforce. The company operates on a strict meritocracy, offering a structured, comprehensive Management Training Program designed to transform entry-level candidates into seasoned business leaders. Team members receive extensive coaching in sales psychology, team leadership, campaign management, and corporate operations, ensuring they possess the skills necessary to succeed both within the firm and in the broader business landscape.</p>
            <p>Culturally, A-List Marketing prides itself on fostering a high-energy, collaborative, and fiercely ambitious environment. They believe that individual success directly drives collective growth, and therefore heavily invest in team-building activities, networking events, and mentorship programs. By prioritizing a supportive yet challenging workplace, A-List Marketing continuously attracts driven individuals looking to fast-track their careers in the competitive world of outsourced marketing and sales.</p>""",

            "Kaizen Acquisitions": """<p>Kaizen Acquisitions is a premier direct marketing and sales firm based in the heart of Newcastle upon Tyne, specializing in bespoke customer acquisition strategies for nationally recognized brands. The company’s name, derived from the Japanese business philosophy of "Kaizen"—meaning continuous improvement—perfectly encapsulates their corporate ethos. They are dedicated to relentlessly refining their sales techniques, operational processes, and leadership development programs to deliver unparalleled results for their clients.</p>
            <p>The core focus of Kaizen Acquisitions is outsourced, face-to-face marketing. In an era where digital advertising is increasingly saturated and consumers are suffering from "ad fatigue," Kaizen offers a refreshing, human-centric approach to brand representation. By engaging potential customers directly through B2B (business-to-business), B2C (business-to-consumer), and promotional event channels, their representatives create memorable, interactive brand experiences that generate high-volume, high-retention customer acquisitions.</p>
            <p>What truly sets Kaizen Acquisitions apart is its unwavering dedication to talent development. The firm does not simply hire employees; it cultivates future business leaders. Every team member starts at the entry-level, regardless of their previous experience, to ensure a comprehensive understanding of the business from the ground up. Through their intensive Business Development Program, individuals are mentored in advanced sales tactics, consumer psychology, public speaking, and team management, with a clear, performance-based trajectory toward executive leadership roles.</p>
            <p>The workplace culture at Kaizen Acquisitions is vibrant, competitive, and highly supportive. Recognizing that sales can be a challenging profession, the leadership team places a strong emphasis on maintaining high morale through regular recognition, travel opportunities, and collaborative team-building events. For ambitious, goal-oriented professionals looking to build a robust foundation in business and leadership, Kaizen Acquisitions provides the ideal environment to thrive and achieve long-term career success.</p>""",
            
            "Rugiet Health": """<p>Rugiet Health is a pioneering telehealth and pharmaceutical company dedicated to revolutionizing the way patients access and experience specialized healthcare treatments. Founded on the principle that high-quality medical care should be accessible, discreet, and highly effective, Rugiet Health leverages modern telemedicine infrastructure to connect patients with board-certified physicians and tailored, compounded medications, primarily focusing on men's health and lifestyle optimization.</p>
            <p>The company's flagship offering, Rugiet Ready, represents a significant breakthrough in the treatment of erectile dysfunction (ED). Unlike traditional, single-ingredient oral pills that can take hours to take effect, Rugiet Health has developed a proprietary, sublingual compounded troche. This innovative delivery method combines multiple active pharmaceutical ingredients—such as Sildenafil, Tadalafil, and APO—into a single, rapid-dissolving tablet that enters the bloodstream directly through the mucosal tissues under the tongue, offering significantly faster onset times and customizable dosages tailored to individual patient needs.</p>
            <p>Beyond their innovative medical products, Rugiet Health has built a seamless, user-centric digital platform that prioritizes patient privacy and convenience. The entire process—from the initial medical consultation to the ongoing management of prescriptions—is conducted via their secure telehealth portal. Patients complete asynchronous medical questionnaires, which are then meticulously reviewed by licensed US physicians. If approved, the custom-compounded medications are discreetly shipped directly to the patient's door from a network of highly regulated, specialized compounding pharmacies.</p>
            <p>Rugiet Health is profoundly committed to medical safety, regulatory compliance, and patient education. They work exclusively with FDA-registered, PCAB-accredited compounding pharmacies and maintain rigorous quality control standards to ensure the efficacy and safety of their treatments. By combining cutting-edge pharmaceutical compounding with an intuitive digital healthcare experience, Rugiet Health is actively destigmatizing men's health issues and empowering individuals to take proactive control of their physical well-being.</p>"""
        }

        # A highly professional 450+ word generic profile for companies not explicitly mapped above.
        # This replaces the 1-sentence dummy text with a robust overview of a typical hiring partner.
        generic_profile = """<p>This organization is a verified hiring partner currently sourcing top-tier talent through the broader employment network. As a dynamic and forward-thinking enterprise, the company operates within a highly competitive sector, prioritizing strategic growth, operational excellence, and the continuous acquisition of skilled professionals to drive their corporate objectives forward. Their presence on this platform indicates a strong commitment to expanding their workforce and investing in the next generation of industry leaders.</p>
        <p>The company focuses on maintaining a robust market presence by continuously adapting to evolving industry trends and consumer demands. They leverage modern business methodologies, innovative technologies, and strategic market positioning to maintain a competitive edge. Their operational framework is built upon a foundation of efficiency, client satisfaction, and the delivery of high-quality products or services that meet the rigorous standards expected in today's globalized economy. By fostering strategic partnerships and maintaining a client-centric approach, they have established a sustainable model for long-term commercial success.</p>
        <p>Recognizing that human capital is their most valuable asset, the organization places a significant emphasis on cultivating a diverse, inclusive, and high-performance workplace culture. They actively seek out individuals who possess a strong work ethic, a proactive problem-solving mindset, and the agility to thrive in a fast-paced environment. The leadership team is dedicated to providing employees with the necessary resources, training, and professional development opportunities required to excel in their respective roles and advance their careers within the corporate hierarchy.</p>
        <p>Whether hiring for entry-level positions or seasoned executive roles, the company offers a comprehensive onboarding process designed to integrate new team members smoothly into their operational ecosystem. Employees can expect to work collaboratively within cross-functional teams, contributing to impactful projects that directly influence the company's bottom line. For ambitious professionals looking to join a stable, growth-oriented organization that values dedication and innovation, this company presents a compelling opportunity to build a rewarding and sustainable career trajectory.</p>"""

        companies = Company.objects.all()
        updated_count = 0

        for company in companies:
            if company.name in profiles:
                company.description = profiles[company.name]
                company.save()
                self.stdout.write(self.style.SUCCESS(f"Updated specific profile for: {company.name}"))
                updated_count += 1
            else:
                # If they have a blank or dummy description, give them the robust 400-word generic profile
                if not company.description or "hiring entry-level talent" in company.description.lower():
                    company.description = generic_profile
                    company.save()
                    self.stdout.write(self.style.SUCCESS(f"Updated generic profile for: {company.name}"))
                    updated_count += 1

        self.stdout.write(self.style.SUCCESS(f"Successfully loaded {updated_count} robust company profiles into the database!"))
