from django.core.management.base import BaseCommand
from apps.jobs.models import Company

class Command(BaseCommand):
    help = 'Seeds highly detailed, authentic company profiles for our curated mid-tier employers.'

    def handle(self, *args, **options):
        profiles = {
            "Hays": """<p>Hays plc is a leading global professional recruiting group, serving both the private and public sectors across 33 countries globally. Established as a titan in the human resources and recruitment industry, Hays employs over 10,000 highly trained experts across hundreds of offices worldwide. The company operates across numerous specialisms, placing candidates into permanent, temporary, and contract roles within industries ranging from Information Technology and Finance to Construction, Healthcare, and Engineering.</p>
            <p>At its core, Hays is driven by a commitment to matching the right talent with the right organizations. They utilize advanced data analytics, proprietary matching algorithms, and deep human expertise to solve complex talent acquisition challenges for their clients. By providing consultative services, Hays goes beyond mere resume parsing; they partner with businesses to architect comprehensive workforce strategies that drive long-term corporate growth.</p>
            <p>For entry-level candidates and graduates, Hays is consistently ranked as a phenomenal starting point. Their internal training programs are highly regarded, offering unparalleled mentorship and exposure to diverse market sectors. Culturally, Hays fosters a deeply collaborative and performance-driven environment, rewarding innovation and dedication while providing robust pathways for rapid career progression.</p>""",

            "Bupa": """<p>Bupa is an international healthcare provision and multi-line insurance group headquartered in the United Kingdom. With origins dating back to 1947, Bupa has evolved into one of the most recognized and trusted healthcare brands globally, serving over 38 million customers across the UK, Australia, Spain, Poland, New Zealand, and parts of Latin America and the Middle East.</p>
            <p>Unlike many traditional corporate entities, Bupa operates under a unique financial structure: they have no shareholders. As a company limited by guarantee, Bupa reinvests all of its profits back into expanding and improving its healthcare services and facilities. This purpose-driven structure ensures that patient care and clinical excellence remain the uncompromising priorities of the organization. Their services span a massive spectrum, including private medical insurance, the operation of hundreds of care homes and dental clinics, and the management of major private hospitals.</p>
            <p>Bupa is highly committed to proactive employee well-being and diversity. They offer significant opportunities for medical professionals, administrative staff, and corporate talent. Their work environment is highly supportive, heavily emphasizing mental health, work-life balance, and continuous professional development for their global workforce.</p>""",

            "Tesco": """<p>Tesco plc is a British multinational groceries and general merchandise retailer, widely recognized as the market leader in the UK supermarket sector and one of the largest retailers in the world by gross revenues. Founded in 1919 by Jack Cohen as a group of market stalls, Tesco has expanded massively, operating thousands of stores and employing over 300,000 individuals worldwide.</p>
            <p>Tesco's operational scope is vast, encompassing enormous hypermarkets (Tesco Extra), standard supermarkets, smaller convenience stores (Tesco Express), and a highly sophisticated online delivery infrastructure. Beyond retail groceries, the corporation has successfully diversified into banking (Tesco Bank), mobile telecommunications (Tesco Mobile), and proprietary data analytics (via their Clubcard loyalty program and Dunnhumby subsidiary).</p>
            <p>As a major employer, Tesco is renowned for its highly accessible career pathways. The company offers some of the most robust graduate schemes, apprenticeships, and retail management training programs in the country. Their corporate culture heavily emphasizes community integration, sustainability, and internal promotion, making it a highly desirable workplace for entry-level candidates seeking stability and long-term career growth.</p>""",

            "Deliveroo": """<p>Deliveroo is a prominent British online food delivery company founded in 2013 by Will Shu and Greg Orlowski. Utilizing sophisticated logistical algorithms and a highly agile gig-economy workforce, Deliveroo connects millions of consumers with thousands of local restaurants, grocery partners, and independent eateries, fundamentally transforming the modern food delivery landscape.</p>
            <p>Operating across multiple countries, Deliveroo’s technological infrastructure is built to handle massive scale and extreme volatility in demand. The company is essentially a logistics and software firm disguised as a food service; they heavily utilize machine learning for dynamic route optimization, predictive preparation times, and real-time fleet management. In recent years, Deliveroo has also expanded into "dark kitchens" (Deliveroo Editions) and rapid grocery delivery (Deliveroo Hop).</p>
            <p>For tech, marketing, and operational talent, Deliveroo represents a fast-paced, highly innovative, and modern corporate environment. The company embraces a startup-like agility while possessing the resources of a publicly traded tech giant. Employees are encouraged to take extreme ownership of projects, driving rapid innovation in a fiercely competitive global market.</p>""",

            "Barclays": """<p>Barclays plc is a historic British multinational universal bank headquartered in London. With roots stretching back to 1690, Barclays operates as one of the "Big Four" banking institutions in the United Kingdom and maintains a highly influential presence in global financial markets, consumer banking, and wealth management.</p>
            <p>The bank is structurally divided into two massive divisions: Barclays UK, which handles retail banking, consumer credit cards, and local business banking; and Barclays International, which encompasses their top-tier corporate and investment banking divisions, along with international credit card operations. This dual structure allows the bank to balance stable consumer revenues with high-growth institutional finance.</p>
            <p>Barclays is widely respected for its rigorous professional development infrastructure. They offer incredibly competitive graduate programs across Investment Banking, Technology, and Retail Management. The corporate culture is highly analytical, deeply focused on regulatory compliance, and currently undergoing a massive digital transformation, making it an excellent environment for candidates interested in Fintech and modern banking infrastructure.</p>""",

            "Vodafone": """<p>Vodafone Group Plc is a British multinational telecommunications company and one of the largest mobile network operators in the world. Operating networks in over 20 countries and partnering with mobile networks in over 40 more, Vodafone provides critical connectivity, broadband, and digital services to hundreds of millions of consumers and corporate enterprises globally.</p>
            <p>Beyond standard consumer mobile plans, Vodafone is a massive player in the Internet of Things (IoT) sector, providing the connective tissue for smart cities, automated logistics, and connected vehicles. The company is actively driving the global rollout of 5G infrastructure, edge computing, and digital security services, positioning itself at the cutting edge of modern communication technologies.</p>
            <p>Vodafone places a massive emphasis on digital innovation and workplace flexibility. Their corporate culture is highly modern, encouraging agile methodologies, continuous upskilling, and global collaboration. The company offers exceptional graduate and apprenticeship schemes, particularly in network engineering, digital marketing, and software development, fostering the next generation of telecom leaders.</p>""",

            "Sky": """<p>Sky Group is a massive British media and telecommunications conglomerate, operating as a primary subsidiary of Comcast. Sky is Europe's leading direct-to-consumer media and entertainment company, boasting millions of subscribers across the UK, Ireland, Germany, Austria, and Italy. They provide broadband internet, mobile network services, and an enormous array of premium television broadcasting.</p>
            <p>As a media powerhouse, Sky is heavily involved in original content production (Sky Studios), continuous news broadcasting (Sky News), and exclusive sports rights (Sky Sports). Technologically, the company is highly advanced, pioneering streaming hardware (Sky Glass and Sky Stream) and sophisticated content delivery networks designed to handle massive concurrent streaming loads during major live events.</p>
            <p>Sky’s workplace is famously vibrant, creative, and highly inclusive. The company operates massive campus-style offices and invests heavily in employee well-being. For professionals in media production, digital marketing, software engineering, and customer relations, Sky offers an incredibly dynamic and culturally rich environment with vast opportunities for lateral and vertical career movement.</p>""",

            "Sainsbury": """<p>J Sainsbury plc, commonly trading as Sainsbury's, is the second-largest chain of supermarkets in the United Kingdom, holding a significant share of the domestic grocery market. Founded in 1869, the company boasts a massive heritage of retail excellence, operating over 1,400 supermarkets and convenience stores across the nation.</p>
            <p>The Sainsbury's corporate umbrella extends far beyond standard groceries. Following the acquisition of Argos and Habitat, the company became a colossal general merchandise retailer. Additionally, Sainsbury's Bank provides financial services ranging from insurance to credit cards. Their operational logistics are immensely complex, requiring highly sophisticated supply chain management to deliver fresh produce and goods daily.</p>
            <p>Sainsbury's is deeply committed to sustainability, aiming to achieve Net Zero carbon emissions across their operations. As an employer, they provide highly structured and supportive training programs. The company culture is deeply rooted in community service, ethical sourcing, and employee empowerment, making it a highly respected and stable corporate home for thousands of entry-level and experienced professionals.</p>""",

            "O2": """<p>O2, legally operating as Virgin Media O2 following a massive joint venture, is a titan in the British telecommunications services sector. The company provides incredibly vital mobile network services, high-speed broadband, and television packages to millions of consumers and businesses across the United Kingdom.</p>
            <p>O2 is famously known for its highly successful brand positioning, customer loyalty programs (O2 Priority), and sponsorship of major entertainment venues (The O2 Arena). The company is at the absolute forefront of deploying 5G networks across the UK and expanding gigabit-capable broadband infrastructure, driving the digital modernization of the country.</p>
            <p>The corporate culture at O2 is highly modern, dynamic, and focused on digital-first strategies. They offer excellent benefits, highly flexible working arrangements, and robust career progression pathways. O2 aggressively recruits talent in digital engineering, marketing, data analytics, and customer experience, providing an energetic and innovative environment for its workforce.</p>""",

            "EE": """<p>EE, originally a joint venture between Deutsche Telekom and Orange, is now a massive brand operating within the BT Group. It stands as one of the largest and most advanced mobile network operators and internet service providers in the United Kingdom, historically famous for being the first company to launch 4G, and subsequently 5G, services in the UK.</p>
            <p>EE focuses heavily on providing the fastest, most reliable network coverage in the nation. The company caters to both individual consumers and massive enterprise clients, offering comprehensive digital solutions, unified communications, and smart home technologies alongside standard mobile services.</p>
            <p>As part of the BT Group, working at EE provides the agility of a dynamic tech brand backed by the massive resources of a national telecom institution. The company highly values technical excellence, customer-centric innovation, and diversity. They offer fantastic graduate schemes and continuous learning opportunities, making EE a highly attractive destination for ambitious professionals entering the tech and telecom sectors.</p>"""
        }

        generic_profile = """<p>This organization is a verified hiring partner currently sourcing top-tier talent through the broader employment network. As a dynamic and forward-thinking enterprise, the company operates within a highly competitive sector, prioritizing strategic growth, operational excellence, and the continuous acquisition of skilled professionals to drive their corporate objectives forward. Their presence on this platform indicates a strong commitment to expanding their workforce and investing in the next generation of industry leaders.</p>
        <p>The company focuses on maintaining a robust market presence by continuously adapting to evolving industry trends and consumer demands. They leverage modern business methodologies, innovative technologies, and strategic market positioning to maintain a competitive edge. Their operational framework is built upon a foundation of efficiency, client satisfaction, and the delivery of high-quality products or services that meet the rigorous standards expected in today's globalized economy. By fostering strategic partnerships and maintaining a client-centric approach, they have established a sustainable model for long-term commercial success.</p>
        <p>Recognizing that human capital is their most valuable asset, the organization places a significant emphasis on cultivating a diverse, inclusive, and high-performance workplace culture. They actively seek out individuals who possess a strong work ethic, a proactive problem-solving mindset, and the agility to thrive in a fast-paced environment. The leadership team is dedicated to providing employees with the necessary resources, training, and professional development opportunities required to excel in their respective roles and advance their careers within the corporate hierarchy.</p>
        <p>Whether hiring for entry-level positions or seasoned executive roles, the company offers a comprehensive onboarding process designed to integrate new team members smoothly into their operational ecosystem. Employees can expect to work collaboratively within cross-functional teams, contributing to impactful projects that directly influence the company's bottom line. For ambitious professionals looking to join a stable, growth-oriented organization that values dedication and innovation, this company presents a compelling opportunity to build a rewarding and sustainable career trajectory.</p>"""

        companies = Company.objects.all()
        updated_count = 0

        for company in companies:
            matched = False
            for target, desc in profiles.items():
                if target.lower() in company.name.lower():
                    company.description = desc
                    company.save()
                    self.stdout.write(self.style.SUCCESS(f"Updated specific profile for: {company.name}"))
                    updated_count += 1
                    matched = True
                    break
            
            if not matched:
                if not company.description or "hiring entry-level talent" in company.description.lower():
                    company.description = generic_profile
                    company.save()
                    self.stdout.write(self.style.SUCCESS(f"Updated generic profile for: {company.name}"))
                    updated_count += 1

        self.stdout.write(self.style.SUCCESS(f"Successfully loaded {updated_count} robust company profiles into the database!"))
